name: Build

on:
  push:
    branches:
    - main
    paths:
    - src/**
  pull_request:
    branches:
    - main
    paths:
    - src/**
  workflow_dispatch: # TODO TO DELETE!

env:
  PROJECT_WORKSPACE: './src'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and test project
        uses: amilochau/github-actions/build/node@amilochau/create-actions-swa #TODO Change to v1!
        with:
          projectWorkspace: ${{ env.PROJECT_WORKSPACE }}
