name: Build

on:
  push:
    branches:
    - main
    paths:
    - src/**
  pull_request:
    branches:
    - main
    paths:
    - src/**

env:
  WORSKPACE_BUILD: './src'
  NODE_VERSION: 16.x

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Restore dependencies
        shell: bash
        run: npm ci
        working-directory: ${{ env.WORSKPACE_BUILD }}
      - name: Build application
        shell: bash
        run: npm run build
        working-directory: ${{ env.WORSKPACE_BUILD }}
      - name: Test application
        shell: bash
        run: npm test --if-present
        working-directory: ${{ env.WORSKPACE_BUILD }}
