name: Deploy application (DEV)

on:
  workflow_dispatch:

concurrency: deploy_app_dev

env:
  PROJECT_WORKSPACE: './src'
  PROJECT_OUTPUT: './src/dist'
  INFRA_DEPLOY_TEMPLATE_PATH: '**/static-web-apps/template.bicep'
  INFRA_DEPLOY_PARAMETERS_PATH: '**/.github/infrastructure/deploy-app.dev.json'
  INFRA_RG_NAME: 'mil-cv-dev-rg'
  INFRA_RG_LOCATION: 'westeurope'
  INFRA_APP_NAME: 'mil-cv-dev-swa'
  TEMPLATES_VERSION: amilochau/add-swa-custom-domains

jobs:
  deploy_infra:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # For parameters file
        with:
          path: cv
      - name: Deploy infrastructure
        uses: amilochau/github-actions/deploy/infrastructure@v1
        with:
          azureTemplateVersion: ${{ env.TEMPLATES_VERSION }}
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
          resourceGroupName: ${{ env.INFRA_RG_NAME }}
          resourceGroupLocation: ${{ env.INFRA_RG_LOCATION }}
          templateFilePath: ${{ env.INFRA_DEPLOY_TEMPLATE_PATH }}
          parametersFilePath: ${{ env.INFRA_DEPLOY_PARAMETERS_PATH }}

  deploy_app:
    name: Deploy application
    needs: deploy_infra
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Azure Functions application
        uses: amilochau/github-actions/deploy/static-web-apps@v1
        with:
          projectWorkspace: ${{ env.PROJECT_WORKSPACE }}
          projectOutput: ${{ env.PROJECT_OUTPUT }}
          azureStaticWebAppsApiToken: ${{ secrets.SWA_TOKEN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
