name: Deploy application (PRD)

on:
  workflow_dispatch:

concurrency: deploy_app_prd

env:
  INFRA_DEPLOY_TEMPLATE_PATH: './templates/static-web-apps/template.bicep'
  INFRA_DEPLOY_PARAMETERS_PATH: './application/.github/infrastructure/deploy-app.prd.json'
  INFRA_RG_NAME: 'mil-cv-prd-rg'
  INFRA_RG_LOCATION: 'westeurope'
  INFRA_APP_NAME: 'mil-cv-prd-swa'
  NODE_ENVIRONMENT: 'Production'
  TEMPLATES_VERSION: v6

jobs:
  deploy_infra:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    environment: PRD
    steps:
      - uses: actions/checkout@v2 # For parameters file
        with:
          path: application
      - name: Deploy infrastructure
        uses: amilochau/github-actions/deploy/infrastructure@v1
        with:
          azureTemplateVersion: ${{ env.TEMPLATES_VERSION }}
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
          resourceGroupName: ${{ env.INFRA_RG_NAME }}
          resourceGroupLocation: ${{ env.INFRA_RG_LOCATION }}
          templateFilePath: ${{ env.INFRA_DEPLOY_TEMPLATE_PATH }}
          parametersFilePath: ${{ env.INFRA_DEPLOY_PARAMETERS_PATH }}

  deploy_app:
    name: Deploy application
    needs: deploy_infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Static Web Apps application
        uses: amilochau/github-actions/deploy/static-web-apps@v1
        with:
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
          applicationName : ${{ env.INFRA_APP_NAME }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
