name: Deploy application (DEV)

on:
  workflow_dispatch:

concurrency: deploy_app_dev

env:
  PROJECT_WORKSPACE: './src'
  PROJECT_OUTPUT: './src/dist'
  INFRA_DEPLOY_TEMPLATE_PATH: './templates/static-web-apps/template.bicep'
  INFRA_DEPLOY_PARAMETERS_PATH: './application/.github/infrastructure/deploy-app.dev.json'
  INFRA_RG_NAME: 'mil-cv-dev-rg'
  INFRA_RG_LOCATION: 'westeurope'
  INFRA_APP_NAME: 'mil-cv-dev-swa'
  TEMPLATES_VERSION: amilochau/fix-repository-branch-swa

jobs:
  deploy_infra:
    name: Deploy infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # For parameters file
        with:
          path: application
      - name: Deploy infrastructure
        id: deploy_infra_step
        uses: amilochau/github-actions/deploy/infrastructure@amilochau/enable-arm-templates-outputs # TODO Set v1 back 
        with:
          azureTemplateVersion: ${{ env.TEMPLATES_VERSION }}
          azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
          resourceGroupName: ${{ env.INFRA_RG_NAME }}
          resourceGroupLocation: ${{ env.INFRA_RG_LOCATION }}
          templateFilePath: ${{ env.INFRA_DEPLOY_TEMPLATE_PATH }}
          parametersFilePath: ${{ env.INFRA_DEPLOY_PARAMETERS_PATH }}
      - run: |
          echo Output:
          echo ${{ steps.deploy_infra_step.outputs.swaName }}
          echo :Tuptuo

  deploy_app:
    name: Deploy application
    needs: deploy_infra
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - run: echo ${{ steps.deploy_infra_step.outputs.swaName }}
      - uses: actions/checkout@v2
      - name: Deploy Azure Functions application
        uses: amilochau/github-actions/deploy/static-web-apps@amilochau/enable-arm-templates-outputs # TODO Set v1 back
        with:
          projectWorkspace: ${{ env.PROJECT_WORKSPACE }}
          projectOutput: ${{ env.PROJECT_OUTPUT }}
          azureStaticWebAppsApiToken: ${{ secrets.SWA_TOKEN }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
